package com.pract.BrainDump.DTO;

import lombok.Data;

@Data
public class CreateNoteRequest {

    private String title;
    private String content;

}



//When creating a note, the client should not send:
//id
//createdAt
//updatedAt
//
//These are generated by the backend. User should only send title and content, hence we are using this DTO instead of full entity.